"""init

Revision ID: 4d2c91a24022
Revises:
Create Date: 2026-03-29 21:54:32.468730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4d2c91a24022"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("plant_country", sa.String(), nullable=True),
        sa.Column("manufacturer", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_brands_name"), "brands", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("role", sa.Enum("admin", "user", name="role"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.create_table(
        "cars",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("model", sa.String(length=50), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("unique_name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cars_brand_id"), "cars", ["brand_id"], unique=False)
    op.create_index(op.f("ix_cars_model"), "cars", ["model"], unique=False)
    op.create_index(op.f("ix_cars_unique_name"), "cars", ["unique_name"], unique=True)
    op.create_index(op.f("ix_cars_year"), "cars", ["year"], unique=False)
    op.create_table(
        "car_images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("car_id", sa.UUID(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column(
            "date_added",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["car_id"],
            ["cars.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "car_specs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("car_id", sa.UUID(), nullable=False),
        sa.Column("body_class", sa.String(), nullable=True),
        sa.Column("engine_type", sa.String(), nullable=True),
        sa.Column("engine_displacement_cylinders", sa.String(), nullable=True),
        sa.Column("horsepower", sa.String(), nullable=True),
        sa.Column("drivetrain", sa.String(), nullable=True),
        sa.Column("torgue", sa.String(), nullable=True),
        sa.Column("top_speed", sa.String(), nullable=True),
        sa.Column("acceleration", sa.String(), nullable=True),
        sa.Column("doors", sa.Integer(), nullable=True),
        sa.Column("seats", sa.Integer(), nullable=True),
        sa.Column("cargo_volume", sa.String(), nullable=True),
        sa.Column("wheel_base", sa.String(), nullable=True),
        sa.Column("HWL", sa.String(), nullable=True),
        sa.Column("fuel_type", sa.String(), nullable=True),
        sa.Column("mpg_tanksize", sa.String(), nullable=True),
        sa.Column("price_range", sa.String(), nullable=True),
        sa.Column("transmmission", sa.String(length=50), nullable=True),
        sa.Column("weight", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["car_id"], ["cars.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_car_specs_car_id"), "car_specs", ["car_id"], unique=False)
    op.create_table(
        "favourites",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("car_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["car_id"], ["cars.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "car_id"),
    )
    op.create_index(
        op.f("ix_favourites_car_id"), "favourites", ["car_id"], unique=False
    )
    op.create_index(
        op.f("ix_favourites_user_id"), "favourites", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_favourites_user_id"), table_name="favourites")
    op.drop_index(op.f("ix_favourites_car_id"), table_name="favourites")
    op.drop_table("favourites")
    op.drop_index(op.f("ix_car_specs_car_id"), table_name="car_specs")
    op.drop_table("car_specs")
    op.drop_table("car_images")
    op.drop_index(op.f("ix_cars_year"), table_name="cars")
    op.drop_index(op.f("ix_cars_unique_name"), table_name="cars")
    op.drop_index(op.f("ix_cars_model"), table_name="cars")
    op.drop_index(op.f("ix_cars_brand_id"), table_name="cars")
    op.drop_table("cars")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_brands_name"), table_name="brands")
    op.drop_table("brands")
    # ### end Alembic commands ###
